name: Pipeline CI-CD Smart Network

on:
  push:
    branches: [ main ]

jobs:
  # المربع الأول: فحص (بدون أخطاء pip)
  Preparation:
    name: Intégration Continue (CI)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Validation du code
        run: echo "Le code est validé et prêt."

  # المربع الثاني: بناء Docker
  Build:
    name: Construction Docker
    needs: Preparation
    runs-on: self-hosted
    steps:
      - name: Build Docker Image
        run: docker build -t network-app .

  # المربع الثالث: النشر
  Deploy:
    name: Déploiement CD
    needs: Build
    runs-on: self-hosted
    steps:
      - name: Deploy Container
        run: |
          docker stop network-app || true
          docker rm network-app || true
          docker run -d --name network-app -p 5000:5000 network-app