name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Vérifier l’application Flask
        run: python app.py