name: PFE Smart Network Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # التغيير هنا: بدلاً من ubuntu-latest نكتب self-hosted
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Run Docker
        run: |
          docker stop network-app || true
          docker rm network-app || true
          docker build -t smart-monitor .
          docker run -d --name network-app -p 5000:5000 smart-monitor